--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (1b53132)
-- Dumped by pg_dump version 17.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS '';


--
-- Name: account_status; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.account_status AS ENUM (
    'active',
    'suspended',
    'banned'
);


ALTER TYPE public.account_status OWNER TO neondb_owner;

--
-- Name: payment_status; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.payment_status AS ENUM (
    'initiated',
    'holding',
    'released',
    'refunded'
);


ALTER TYPE public.payment_status OWNER TO neondb_owner;

--
-- Name: service_activity; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.service_activity AS ENUM (
    'active',
    'inactive'
);


ALTER TYPE public.service_activity OWNER TO neondb_owner;

--
-- Name: service_request_status; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.service_request_status AS ENUM (
    'pending',
    'accepted',
    'declined',
    'in_progress',
    'completed',
    'cancelled',
    'expired'
);


ALTER TYPE public.service_request_status OWNER TO neondb_owner;

--
-- Name: service_status; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.service_status AS ENUM (
    'active',
    'in_progress',
    'completed',
    'cancelled'
);


ALTER TYPE public.service_status OWNER TO neondb_owner;

--
-- Name: status; Type: TYPE; Schema: public; Owner: neondb_owner
--

CREATE TYPE public.status AS ENUM (
    'created',
    'ongoing',
    'done',
    'cancelled'
);


ALTER TYPE public.status OWNER TO neondb_owner;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ads_watching_history; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.ads_watching_history (
    id integer NOT NULL,
    user_id text NOT NULL,
    date_time timestamptz NOT NULL
);


ALTER TABLE public.ads_watching_history OWNER TO neondb_owner;

--
-- Name: ads_watching_history_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.ads_watching_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ads_watching_history_id_seq OWNER TO neondb_owner;

--
-- Name: ads_watching_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.ads_watching_history_id_seq OWNED BY public.ads_watching_history.id;


--
-- Name: notification_events; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.notification_events (
    type character varying NOT NULL,
    target_id integer NOT NULL,
    created_at timestamptz NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.notification_events OWNER TO neondb_owner;

--
-- Name: notification_events_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.notification_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notification_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    message text NOT NULL,
    recipient_user_id text NOT NULL,
    action_user_id text NOT NULL,
    is_read boolean NOT NULL,
    event_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO neondb_owner;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.payments (
    id integer NOT NULL,
    service_request_id integer NOT NULL,
    payer_id text NOT NULL,
    amount_tokens integer NOT NULL,
    status public.payment_status NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);


ALTER TABLE public.payments OWNER TO neondb_owner;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.payments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payments_id_seq OWNER TO neondb_owner;

--
-- Name: payments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.payments_id_seq OWNED BY public.payments.id;


--
-- Name: redeemed_rewards; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.redeemed_rewards (
    id integer NOT NULL,
    reward_id integer NOT NULL,
    user_id text NOT NULL,
    redeemed_at timestamptz NOT NULL,
    cost integer NOT NULL
);


ALTER TABLE public.redeemed_rewards OWNER TO neondb_owner;

--
-- Name: redeemed_rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.redeemed_rewards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.redeemed_rewards_id_seq OWNER TO neondb_owner;

--
-- Name: redeemed_rewards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.redeemed_rewards_id_seq OWNED BY public.redeemed_rewards.id;


--
-- Name: reports; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.reports (
    id integer NOT NULL,
    listing_id integer NOT NULL,
    reporter_id text NOT NULL,
    datetime timestamptz NOT NULL,
    report_reason text,
    status text NOT NULL
);


ALTER TABLE public.reports OWNER TO neondb_owner;

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.reviews (
    id integer NOT NULL,
    request_id integer NOT NULL,
    reviewer_id text NOT NULL,
    reviewee_id text NOT NULL,
    rating integer NOT NULL,
    comment text,
    date_time timestamptz NOT NULL
);


ALTER TABLE public.reviews OWNER TO neondb_owner;

--
-- Name: service_requests; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.service_requests (
    id integer NOT NULL,
    listing_id integer NOT NULL,
    requester_id text NOT NULL,
    provider_id text NOT NULL,
    status_detail public.service_request_status NOT NULL,
    activity public.service_activity NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    token_reward integer NOT NULL
);


ALTER TABLE public.service_requests OWNER TO neondb_owner;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.reviews_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reviews_id_seq OWNER TO neondb_owner;

--
-- Name: reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.reviews_id_seq OWNED BY public.service_requests.id;


--
-- Name: reviews_id_seq1; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.reviews_id_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reviews_id_seq1 OWNER TO neondb_owner;

--
-- Name: reviews_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.reviews_id_seq1 OWNED BY public.reviews.id;


--
-- Name: rewards; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.rewards (
    id integer NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    cost integer NOT NULL,
    available_amount integer NOT NULL,
    image_url character varying,
    created_date timestamptz NOT NULL,
    coupon_code character varying NOT NULL
);


ALTER TABLE public.rewards OWNER TO neondb_owner;

--
-- Name: rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.rewards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rewards_id_seq OWNER TO neondb_owner;

--
-- Name: rewards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.rewards_id_seq OWNED BY public.rewards.id;


--
-- Name: service_listings; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.service_listings (
    id integer NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    token_reward integer NOT NULL,
    posted_by text NOT NULL,
    posted_at timestamptz NOT NULL,
    category text NOT NULL,
    image_url text
);


ALTER TABLE public.service_listings OWNER TO neondb_owner;

--
-- Name: service_listings_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.service_listings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.service_listings_id_seq OWNER TO neondb_owner;

--
-- Name: service_listings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.service_listings_id_seq OWNED BY public.service_listings.id;


--
-- Name: service_request_completion; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.service_request_completion (
    id integer NOT NULL,
    request_id integer NOT NULL,
    requester_completed boolean NOT NULL,
    provider_completed boolean NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.service_request_completion OWNER TO neondb_owner;

--
-- Name: services_request_completion_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.services_request_completion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.services_request_completion_id_seq OWNER TO neondb_owner;

--
-- Name: services_request_completion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.services_request_completion_id_seq OWNED BY public.service_request_completion.id;


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.transactions (
    id integer NOT NULL,
    user_id text NOT NULL,
    type text NOT NULL,
    amount integer NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);


ALTER TABLE public.transactions OWNER TO neondb_owner;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.transactions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transactions_id_seq OWNER TO neondb_owner;

--
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.users (
    id text NOT NULL,
    phone text NOT NULL,
    token_balance integer NOT NULL,
    status public.account_status NOT NULL,
    address_line_1 text NOT NULL,
    address_line_2 text NOT NULL,
    city text NOT NULL,
    state_province text NOT NULL,
    zip_postal_code text NOT NULL,
    country text NOT NULL,
    joined_at timestamptz NOT NULL,
    email boolean NOT NULL,
    full_name text NOT NULL,
    avg_rating real NOT NULL
);


ALTER TABLE public.users OWNER TO neondb_owner;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO neondb_owner;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: ads_watching_history id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ads_watching_history ALTER COLUMN id SET DEFAULT nextval('public.ads_watching_history_id_seq'::regclass);


--
-- Name: payments id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.payments ALTER COLUMN id SET DEFAULT nextval('public.payments_id_seq'::regclass);


--
-- Name: redeemed_rewards id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.redeemed_rewards ALTER COLUMN id SET DEFAULT nextval('public.redeemed_rewards_id_seq'::regclass);


--
-- Name: reviews id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews ALTER COLUMN id SET DEFAULT nextval('public.reviews_id_seq1'::regclass);


--
-- Name: rewards id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rewards ALTER COLUMN id SET DEFAULT nextval('public.rewards_id_seq'::regclass);


--
-- Name: service_listings id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_listings ALTER COLUMN id SET DEFAULT nextval('public.service_listings_id_seq'::regclass);


--
-- Name: service_request_completion id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_request_completion ALTER COLUMN id SET DEFAULT nextval('public.services_request_completion_id_seq'::regclass);


--
-- Name: service_requests id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_requests ALTER COLUMN id SET DEFAULT nextval('public.reviews_id_seq'::regclass);


--
-- Name: transactions id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.transactions ALTER COLUMN id SET DEFAULT nextval('public.transactions_id_seq'::regclass);


--
-- Name: ads_watching_history ads_watching_history_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ads_watching_history
    ADD CONSTRAINT ads_watching_history_pk PRIMARY KEY (id);


--
-- Name: notification_events notification_events_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.notification_events
    ADD CONSTRAINT notification_events_pk PRIMARY KEY (id);


--
-- Name: notifications notifications_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pk PRIMARY KEY (id);


--
-- Name: payments payments_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pk PRIMARY KEY (id);


--
-- Name: redeemed_rewards redeemed_rewards_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.redeemed_rewards
    ADD CONSTRAINT redeemed_rewards_pk PRIMARY KEY (id);


--
-- Name: reports reports_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pk PRIMARY KEY (id);


--
-- Name: service_requests requests_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT requests_pk PRIMARY KEY (id);


--
-- Name: reviews reviews_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pk PRIMARY KEY (id);


--
-- Name: reviews reviews_unique; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_unique UNIQUE (request_id);


--
-- Name: rewards rewards_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT rewards_pk PRIMARY KEY (id);


--
-- Name: service_listings service_listings_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_listings
    ADD CONSTRAINT service_listings_pk PRIMARY KEY (id);


--
-- Name: service_request_completion services_request_completion_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_request_completion
    ADD CONSTRAINT services_request_completion_pk PRIMARY KEY (id);


--
-- Name: transactions transactions_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pk PRIMARY KEY (id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- Name: users users_unique; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_unique UNIQUE (id);


--
-- Name: ads_watching_history ads_watching_history_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ads_watching_history
    ADD CONSTRAINT ads_watching_history_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notifications notifications_notification_events_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_notification_events_fk FOREIGN KEY (event_id) REFERENCES public.notification_events(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_users_action_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_users_action_fk FOREIGN KEY (action_user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: notifications notifications_users_recipient_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_users_recipient_fk FOREIGN KEY (recipient_user_id) REFERENCES public.users(id);


--
-- Name: payments payments_service_requests_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_service_requests_fk FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;


--
-- Name: payments payments_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_users_fk FOREIGN KEY (payer_id) REFERENCES public.users(id);


--
-- Name: redeemed_rewards redeemed_rewards_rewards_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.redeemed_rewards
    ADD CONSTRAINT redeemed_rewards_rewards_fk FOREIGN KEY (reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: redeemed_rewards redeemed_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.redeemed_rewards
    ADD CONSTRAINT redeemed_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: reports reports_service_listings_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_service_listings_fk_1 FOREIGN KEY (listing_id) REFERENCES public.service_listings(id);


--
-- Name: reports reports_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_users_fk FOREIGN KEY (reporter_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: reviews reviews_service_requests_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_service_requests_fk FOREIGN KEY (request_id) REFERENCES public.service_requests(id);


--
-- Name: reviews reviews_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id);


--
-- Name: reviews reviews_users_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_users_fk_1 FOREIGN KEY (reviewee_id) REFERENCES public.users(id);


--
-- Name: service_listings service_listings_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_listings
    ADD CONSTRAINT service_listings_users_fk FOREIGN KEY (posted_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: service_requests service_requests_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_users_fk FOREIGN KEY (provider_id) REFERENCES public.users(id);


--
-- Name: service_requests service_requests_users_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_users_fk_1 FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- Name: service_request_completion services_request_completion_service_requests_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_request_completion
    ADD CONSTRAINT services_request_completion_service_requests_fk FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;


--
-- Name: transactions transactions_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--
