// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReport = `-- name: InsertReport :exec
INSERT INTO reports (listing_id,reporter_id,datetime,report_reason,status,additional_detail)
VALUES ($1,$2,NOW(),$3,'pending',$4)
`

type InsertReportParams struct {
	ListingID        int32       `json:"listing_id"`
	ReporterID       string      `json:"reporter_id"`
	ReportReason     pgtype.Text `json:"report_reason"`
	AdditionalDetail pgtype.Text `json:"additional_detail"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.ListingID,
		arg.ReporterID,
		arg.ReportReason,
		arg.AdditionalDetail,
	)
	return err
}
