// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repository

import (
	"context"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO "transaction" (user_id,type,amount,created_at)
SELECT
$1,$2,p.amount_tokens,NOW()
FROM payment p
WHERE p.id = $3
`

type InsertTransactionParams struct {
	UserID    string `json:"user_id"`
	Type      string `json:"type"`
	PaymentID int32  `json:"payment_id"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction, arg.UserID, arg.Type, arg.PaymentID)
	return err
}
