// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deductToken = `-- name: DeductToken :execresult
UPDATE users
SET token_balance = $1
WHERE id = $2
`

type DeductTokenParams struct {
	TokenBalance int32  `json:"token_balance"`
	ID           string `json:"id"`
}

func (q *Queries) DeductToken(ctx context.Context, arg DeductTokenParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deductToken, arg.TokenBalance, arg.ID)
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, id)
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, phone, token_balance, status, address_line_1, address_line_2, city, state_province, zip_postal_code, country, joined_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.TokenBalance,
		&i.Status,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.ZipPostalCode,
		&i.Country,
		&i.JoinedAt,
	)
	return i, err
}

const getUserTokenBalance = `-- name: GetUserTokenBalance :one
SELECT token_balance FROM users
WHERE id = $1
`

func (q *Queries) GetUserTokenBalance(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserTokenBalance, id)
	var token_balance int32
	err := row.Scan(&token_balance)
	return token_balance, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id,first_name,last_name,phone,token_balance,status,address_line_1,address_line_2,city,state_province,zip_postal_code,country,joined_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW())
RETURNING id
`

type InsertUserParams struct {
	ID            string        `json:"id"`
	FirstName     string        `json:"first_name"`
	LastName      string        `json:"last_name"`
	Phone         string        `json:"phone"`
	TokenBalance  int32         `json:"token_balance"`
	Status        AccountStatus `json:"status"`
	AddressLine1  string        `json:"address_line_1"`
	AddressLine2  string        `json:"address_line_2"`
	City          string        `json:"city"`
	StateProvince string        `json:"state_province"`
	ZipPostalCode string        `json:"zip_postal_code"`
	Country       string        `json:"country"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.TokenBalance,
		arg.Status,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateProvince,
		arg.ZipPostalCode,
		arg.Country,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET first_name = $1, last_name = $2, phone = $3, address_line_1 = $4, address_line_2 = $5, city = $6, state_province = $7, zip_postal_code = $8, country = $9
WHERE id = $10
`

type UpdateUserParams struct {
	FirstName     string `json:"first_name"`
	LastName      string `json:"last_name"`
	Phone         string `json:"phone"`
	AddressLine1  string `json:"address_line_1"`
	AddressLine2  string `json:"address_line_2"`
	City          string `json:"city"`
	StateProvince string `json:"state_province"`
	ZipPostalCode string `json:"zip_postal_code"`
	Country       string `json:"country"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateProvince,
		arg.ZipPostalCode,
		arg.Country,
		arg.ID,
	)
}
